/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lliga;

/**
 *
 * @author Maribel
 */
public class frmEquips extends javax.swing.JFrame {
    
    private Equips llistaEquips;

    /**
     * Creates new form frmEquips
     */
    public frmEquips() {
        initComponents(); 
        llistaEquips = new Equips();
        llistaEquips.obtenirEquips();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrimer = new java.awt.Button();
        btnAnterior = new java.awt.Button();
        btnSeguent = new java.awt.Button();
        btnUltim = new java.awt.Button();
        btnSortir = new java.awt.Button();
        java.awt.Label lblIdEquip = new java.awt.Label();
        lblNomEquip = new java.awt.Label();
        lblEstadi = new java.awt.Label();
        lblPoblacio = new java.awt.Label();
        lblCodiPostal = new java.awt.Label();
        txtIdEquip = new java.awt.TextField();
        txtNomEquip = new java.awt.TextField();
        txtEstadi = new java.awt.TextField();
        txtPoblacio = new java.awt.TextField();
        txtCodPostal = new java.awt.TextField();
        btnEliminar = new java.awt.Button();
        btnAfegir = new java.awt.Button();
        btnCancelar = new java.awt.Button();
        btnAcceptar = new java.awt.Button();
        btnMostrar = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(433, 335));
        setResizable(false);

        btnPrimer.setActionCommand("primer");
        btnPrimer.setLabel("<<");
        btnPrimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerActionPerformed(evt);
            }
        });

        btnAnterior.setActionCommand("anterior");
        btnAnterior.setLabel("<");
        btnAnterior.setName(""); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSeguent.setActionCommand("seguent");
        btnSeguent.setLabel(">");
        btnSeguent.setName(""); // NOI18N
        btnSeguent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguentActionPerformed(evt);
            }
        });

        btnUltim.setActionCommand("ultim");
        btnUltim.setLabel(">>");
        btnUltim.setName(""); // NOI18N
        btnUltim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimActionPerformed(evt);
            }
        });

        btnSortir.setLabel("Sortir");
        btnSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortirActionPerformed(evt);
            }
        });

        lblIdEquip.setName(""); // NOI18N
        lblIdEquip.setText("Id Equip");

        lblNomEquip.setName(""); // NOI18N
        lblNomEquip.setText("Nom Equip");

        lblEstadi.setName(""); // NOI18N
        lblEstadi.setText("Estadi");

        lblPoblacio.setName(""); // NOI18N
        lblPoblacio.setText("Població");

        lblCodiPostal.setName(""); // NOI18N
        lblCodiPostal.setText("Codi Postal");

        txtIdEquip.setEditable(false);
        txtIdEquip.setName(""); // NOI18N
        txtIdEquip.setEnabled(false);

        txtNomEquip.setName(""); // NOI18N

        txtEstadi.setName(""); // NOI18N

        txtPoblacio.setName(""); // NOI18N

        txtCodPostal.setName(""); // NOI18N

        btnEliminar.setActionCommand("primer");
        btnEliminar.setLabel("-");
        btnEliminar.setName(""); // NOI18N
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAfegir.setActionCommand("primer");
        btnAfegir.setLabel("+");
        btnAfegir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAfegirActionPerformed(evt);
            }
        });

        btnCancelar.setActionCommand("primer");
        btnCancelar.setLabel("Cancelar");
        btnCancelar.setName(""); // NOI18N
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnAcceptar.setActionCommand("primer");
        btnAcceptar.setLabel("Acceptar");
        btnAcceptar.setName(""); // NOI18N
        btnAcceptar.setEnabled(false);
        btnAcceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptarActionPerformed(evt);
            }
        });

        btnMostrar.setLabel("Mostrar jugadors");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPoblacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodiPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNomEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadi, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPoblacio, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodPostal, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnUltim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSortir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPrimer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAfegir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(btnAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSeguent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIdEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEstadi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEstadi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPoblacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPoblacio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCodiPostal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCodPostal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUltim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSeguent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAfegir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSortir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAcceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMostrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))))
        );

        btnPrimer.getAccessibleContext().setAccessibleName("primer");
        btnAnterior.getAccessibleContext().setAccessibleName("anterior");
        btnSeguent.getAccessibleContext().setAccessibleName("seguent");
        btnUltim.getAccessibleContext().setAccessibleName("ultim");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Captura de l'event clic del botó Sortir.
 * Tanca el formulari i l'aplicació
 * @param evt 
 */
    private void btnSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortirActionPerformed
        // Per tal de tancar el formulari l'hem d'amagar (setVisible(false)) i matar-lo
        // (dispose)
    
        setVisible(false);
        dispose();
    
        // Per últim matem l'aplicació. 
        System.exit(0); 
    }//GEN-LAST:event_btnSortirActionPerformed
/**
 * Captura de l'event clic del botó Primer.
 * Mostra el primer registre de la taula Equips
 * @param evt 
 */
    private void btnPrimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerActionPerformed
        modificarEquips();
        Primer();
    }//GEN-LAST:event_btnPrimerActionPerformed
/**
 * Captura de l'event clic del botó Anterior.
 * Mostra el registre anterior a l'actual de la taula Equips
 * @param evt 
 */
    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        modificarEquips();
        Anterior();
    }//GEN-LAST:event_btnAnteriorActionPerformed
/**
 * Captura de l'event clic del botó Següent.
 * Mostra el registre següent a l'actual de la taula Equips
 * @param evt 
 */
    private void btnSeguentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguentActionPerformed
        modificarEquips();
        Seguent();
    }//GEN-LAST:event_btnSeguentActionPerformed
/**
 * Captura de l'event clic del botó Últim.
 * Mostra el darrer registre de la taula Equips
 * @param evt 
 */
    private void btnUltimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimActionPerformed
        modificarEquips();
        Ultim();
    }//GEN-LAST:event_btnUltimActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        Eliminar();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAfegirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAfegirActionPerformed
        Afegir();
    }//GEN-LAST:event_btnAfegirActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Actual();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAcceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptarActionPerformed
        afegirEquip();
    }//GEN-LAST:event_btnAcceptarActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        mostrarJugadors();
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEquips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEquips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEquips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEquips.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmEquips frm = new frmEquips();
                frm.setVisible(true);
                frm.Primer();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAcceptar;
    private java.awt.Button btnAfegir;
    private java.awt.Button btnAnterior;
    private java.awt.Button btnCancelar;
    private java.awt.Button btnEliminar;
    private java.awt.Button btnMostrar;
    private java.awt.Button btnPrimer;
    private java.awt.Button btnSeguent;
    private java.awt.Button btnSortir;
    private java.awt.Button btnUltim;
    private java.awt.Label lblCodiPostal;
    private java.awt.Label lblEstadi;
    private java.awt.Label lblNomEquip;
    private java.awt.Label lblPoblacio;
    private java.awt.TextField txtCodPostal;
    private java.awt.TextField txtEstadi;
    private java.awt.TextField txtIdEquip;
    private java.awt.TextField txtNomEquip;
    private java.awt.TextField txtPoblacio;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Mostra el primer registre de la taula Equips
     */
    private void Primer(){
        /*Insereix aquí el codi per mostrar el primer registre,
        Ha de fer la crida a primer, i passar l'objecte Equip que
        retorna aquest mètode a la funció mostrarEquip(eq)*/
        Equip equip = llistaEquips.primer();
        mostrarEquip(equip);
    }

     /**
     * Mostra el registre anterior
     */
    private void Anterior(){
        /*Insereix aquí el codi per mostrar el primer registre*/
        Equip equip = llistaEquips.anterior();
        mostrarEquip(equip);
    }

     /**
     * Mostra el registre següent
     */
    private void Seguent(){
        /*Insereix aquí el codi per mostrar el primer registre*/
        Equip equip = llistaEquips.posterior();
        mostrarEquip(equip);
    }
     /**
     * Mostra el darrer registre
     */
    private void Ultim(){
        /*Insereix aquí el codi per mostrar el primer registre*/
        Equip equip = llistaEquips.ultim();
        mostrarEquip(equip);
    }
    
    private void Actual(){
        Equip equip = llistaEquips.actual();
        mostrarEquip(equip);
    }
    
    private void Afegir(){
        borrarDades();
        btnAcceptar.setEnabled(true);
        btnCancelar.setEnabled(true);
        btnPrimer.setEnabled(false);
        btnAnterior.setEnabled(false);
        btnSeguent.setEnabled(false);
        btnUltim.setEnabled(false);
        btnAfegir.setEnabled(false);
        btnEliminar.setEnabled(false);
        btnMostrar.setEnabled(false);
    }
    
    private void Eliminar(){
        int comprovacio = javax.swing.JOptionPane.showConfirmDialog(null, "Vols eliminar el registre?", "Eliminar registre", javax.swing.JOptionPane.YES_NO_OPTION);
        if (comprovacio == 0) {
            llistaEquips.eliminarEquip();
            Actual();
        }
    }

     /**
     * Mostra el registre anterior
     * @param equip Dades de l'objecte equip a mostrar
     */
    private void mostrarEquip(Equip equip){
        if (equip != null) {
            txtNomEquip.setEditable(true);
            txtEstadi.setEditable(true);
            txtPoblacio.setEditable(true);
            txtCodPostal.setEditable(true);
            btnEliminar.setEnabled(true);
            txtIdEquip.setText(Integer.toString(equip.getEqId()));
            txtNomEquip.setText(equip.getEqNom());
            txtEstadi.setText(equip.getEstadi());
            txtPoblacio.setText(equip.getPoblacio());
            txtCodPostal.setText(equip.getCodPostal());
            actualitzarBotons();
        }
        else {
            txtNomEquip.setEditable(false);
            txtEstadi.setEditable(false);
            txtPoblacio.setEditable(false);
            txtCodPostal.setEditable(false);
            btnEliminar.setEnabled(false);
            btnPrimer.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnSeguent.setEnabled(false);
            btnUltim.setEnabled(false);
        }
    }
    
    private void mostrarJugadors() {
        frmJugadors jugadors = new frmJugadors();
        jugadors.idEquip = Integer.parseInt(txtIdEquip.getText());
        jugadors.getLlistaJugadors();
        jugadors.setVisible(true);
    }
    
    private void borrarDades() {
        txtIdEquip.setText("");
        txtNomEquip.setText("");
        txtEstadi.setText("");
        txtPoblacio.setText("");
        txtCodPostal.setText("");
    }
    
     /**
     * Activa o desactiva els botons en funció de si estem en el primer o darrer
     * registre
     * @param pucEnrere true si puc tirar enrere, false en cas contrari
     * @param pucEndavant true si puc tirar endavant, false en cas contrari
     */
    private void actualitzarBotons(){
        
        /*Aquest mètode hauria d'activar o desactivar els botons
        en funció de si estem o no en el primer registre o l'últim*/
        btnPrimer.setEnabled(llistaEquips.pucEnrere());
        btnAnterior.setEnabled(llistaEquips.pucEnrere());
        btnSeguent.setEnabled(llistaEquips.pucEndavant());
        btnUltim.setEnabled(llistaEquips.pucEndavant());
        btnAcceptar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnAfegir.setEnabled(true);
        btnEliminar.setEnabled(true);
        btnMostrar.setEnabled(true);
    }

     /**
     * Recupera les dades del formulari i les carrega en un objecte Equip
     */
    private Equip recuperarEquip() {
        Equip equip = new Equip();
        /*Caldria comprovar que les dades són correctes, idequip numèric,
        codi postal numèric de 5 xifres, etc*/
        equip.setEqId(Integer.parseInt(txtIdEquip.getText()));
        equip.setEqNom(txtNomEquip.getText());
        equip.setEstadi(txtEstadi.getText());
        equip.setPoblacio(txtPoblacio.getText());
        equip.setCodPostal(txtCodPostal.getText());
        return equip;
    }
    
    private void afegirEquip() {
        txtIdEquip.setText(Integer.toString(-1));
        Equip equip = recuperarEquip();
        Equips.afegirEquip(equip);
        Equips.obtenirEquips();
        Ultim();
    }
    
    private void modificarEquips() {
        Equip equip = recuperarEquip();
        if (llistaEquips.actual().compareTo(equip) != 0) {
            llistaEquips.updateEquip(equip);
        }
    }
    
    /*
    Feu una ullada als mètodes:
    private void btnSortirActionPerformed(java.awt.event.ActionEvent evt)
    private void btnPrimerActionPerformed(java.awt.event.ActionEvent evt)
    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt)
    private void btnSeguentActionPerformed(java.awt.event.ActionEvent evt)
    private void btnUltimActionPerformed(java.awt.event.ActionEvent evt)
    public static void main(String args[])
    */

    /*
    *  Entre els atributs privats de la classe necessitarem un objecte de tipus Equips
    *  dels que heu creat als vostres projectes, Aquest objecte l'haureu d'inicialitzar
    *  en el main. En els mètodes primer, anterior, últim, seguent haureu de cridar els
    *  mètodes corresponents de l'objecte Equips que teniu en memòria
    *  Haureu d'afegir, si és que no ho teniu, a la Classe Equips un mètode que us indiqui
    *  si podeu tirar enrere i un altre que us indiqui si podeu tirar endavant. D'aquesta
    *  manera podreu activar i desactivar els corresponents botons.
    *
    */

}