/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lliga;

/**
 *
 * @author Maribel
 */
public class frmJugadors extends javax.swing.JFrame {
    
    private Jugadors llistaJugadors;
    int idEquip;

    /**
     * Creates new form frmEquips
     */
    public frmJugadors() {
        initComponents(); 
        llistaJugadors = new Jugadors();
        llistaJugadors.obtenirJugadors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrimer = new java.awt.Button();
        btnAnterior = new java.awt.Button();
        btnSeguent = new java.awt.Button();
        btnUltim = new java.awt.Button();
        btnSortir = new java.awt.Button();
        java.awt.Label lblIdJugador = new java.awt.Label();
        lblIdEquip = new java.awt.Label();
        lblNomJugador = new java.awt.Label();
        lblDorsal = new java.awt.Label();
        lblEdat = new java.awt.Label();
        txtIdJugador = new java.awt.TextField();
        txtIdEquip = new java.awt.TextField();
        txtNomJugador = new java.awt.TextField();
        txtDorsal = new java.awt.TextField();
        txtEdat = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnPrimer.setActionCommand("primer");
        btnPrimer.setLabel("<<");
        btnPrimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimerActionPerformed(evt);
            }
        });

        btnAnterior.setActionCommand("anterior");
        btnAnterior.setLabel("<");
        btnAnterior.setName(""); // NOI18N
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSeguent.setActionCommand("seguent");
        btnSeguent.setLabel(">");
        btnSeguent.setName(""); // NOI18N
        btnSeguent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguentActionPerformed(evt);
            }
        });

        btnUltim.setActionCommand("ultim");
        btnUltim.setLabel(">>");
        btnUltim.setName(""); // NOI18N
        btnUltim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimActionPerformed(evt);
            }
        });

        btnSortir.setLabel("Sortir");
        btnSortir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortirActionPerformed(evt);
            }
        });

        lblIdJugador.setName(""); // NOI18N
        lblIdJugador.setText("Id Jugador");

        lblIdEquip.setName(""); // NOI18N
        lblIdEquip.setText("Id Equip");

        lblNomJugador.setName(""); // NOI18N
        lblNomJugador.setText("Nom Jugador");

        lblDorsal.setName(""); // NOI18N
        lblDorsal.setText("Dorsal");

        lblEdat.setName(""); // NOI18N
        lblEdat.setText("Edat");

        txtIdJugador.setEditable(false);
        txtIdJugador.setName(""); // NOI18N
        txtIdJugador.setEnabled(false);

        txtIdEquip.setName(""); // NOI18N

        txtNomJugador.setName(""); // NOI18N

        txtDorsal.setName(""); // NOI18N

        txtEdat.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblIdJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEdat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIdEquip, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNomJugador, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEdat, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnSortir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(btnUltim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnPrimer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136)
                .addComponent(btnSeguent, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtIdJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblIdJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdEquip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdEquip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomJugador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDorsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDorsal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEdat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtEdat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUltim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSeguent, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrimer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAnterior, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSortir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(31, 31, 31))
        );

        btnPrimer.getAccessibleContext().setAccessibleName("primer");
        btnAnterior.getAccessibleContext().setAccessibleName("anterior");
        btnSeguent.getAccessibleContext().setAccessibleName("seguent");
        btnUltim.getAccessibleContext().setAccessibleName("ultim");

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**
 * Captura de l'event clic del botó Sortir.
 * Tanca el formulari i l'aplicació
 * @param evt 
 */
    private void btnSortirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortirActionPerformed
        // Per tal de tancar el formulari l'hem d'amagar (setVisible(false)) i matar-lo
        // (dispose)
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnSortirActionPerformed
/**
 * Captura de l'event clic del botó Primer.
 * Mostra el primer registre de la taula Equips
 * @param evt 
 */
    private void btnPrimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimerActionPerformed
        modificarJugadors();
        Primer();
    }//GEN-LAST:event_btnPrimerActionPerformed
/**
 * Captura de l'event clic del botó Anterior.
 * Mostra el registre anterior a l'actual de la taula Equips
 * @param evt 
 */
    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        modificarJugadors();
        Anterior();
    }//GEN-LAST:event_btnAnteriorActionPerformed
/**
 * Captura de l'event clic del botó Següent.
 * Mostra el registre següent a l'actual de la taula Equips
 * @param evt 
 */
    private void btnSeguentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguentActionPerformed
        modificarJugadors();
        Seguent();
    }//GEN-LAST:event_btnSeguentActionPerformed
/**
 * Captura de l'event clic del botó Últim.
 * Mostra el darrer registre de la taula Equips
 * @param evt 
 */
    private void btnUltimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimActionPerformed
        modificarJugadors();
        Ultim();
    }//GEN-LAST:event_btnUltimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJugadors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJugadors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJugadors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJugadors.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmJugadors frm = new frmJugadors();
                frm.setVisible(true);
                frm.Primer();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnAnterior;
    private java.awt.Button btnPrimer;
    private java.awt.Button btnSeguent;
    private java.awt.Button btnSortir;
    private java.awt.Button btnUltim;
    private java.awt.Label lblDorsal;
    private java.awt.Label lblEdat;
    private java.awt.Label lblIdEquip;
    private java.awt.Label lblNomJugador;
    private java.awt.TextField txtDorsal;
    private java.awt.TextField txtEdat;
    private java.awt.TextField txtIdEquip;
    private java.awt.TextField txtIdJugador;
    private java.awt.TextField txtNomJugador;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Mostra el primer registre de la taula Equips
     */
    private void Primer(){
        /*Insereix aquí el codi per mostrar el primer registre,
        Ha de fer la crida a primer, i passar l'objecte Equip que
        retorna aquest mètode a la funció mostrarEquip(eq)*/
        Jugador jugador = llistaJugadors.primer();
        mostrarJugador(jugador);
    }

     /**
     * Mostra el registre anterior
     */
    private void Anterior(){
        /*Insereix aquí el codi per mostrar el primer registre*/
        Jugador jugador = llistaJugadors.anterior();
        mostrarJugador(jugador);
    }

     /**
     * Mostra el registre següent
     */
    private void Seguent(){
        /*Insereix aquí el codi per mostrar el primer registre*/
        Jugador jugador = llistaJugadors.posterior();
        mostrarJugador(jugador);
    }
     /**
     * Mostra el darrer registre
     */
    private void Ultim(){
        /*Insereix aquí el codi per mostrar el primer registre*/
        Jugador jugador = llistaJugadors.ultim();
        mostrarJugador(jugador);
    }

     /**
     * Mostra el registre anterior
     * @param equip Dades de l'objecte equip a mostrar
     */
    private void mostrarJugador(Jugador jugador){
        if (jugador != null) {
            txtIdEquip.setEditable(true);
            txtNomJugador.setEditable(true);
            txtDorsal.setEditable(true);
            txtEdat.setEditable(true);
            txtIdJugador.setText(Integer.toString(jugador.getJugId()));
            txtIdEquip.setText(Integer.toString(jugador.getEqId()));
            txtNomJugador.setText(jugador.getJugNom());
            txtDorsal.setText(Integer.toString(jugador.getDorsal()));
            txtEdat.setText(Integer.toString(jugador.getEdat()));
            actualitzarBotons();
        }
        else {
            txtIdEquip.setEditable(false);
            txtNomJugador.setEditable(false);
            txtDorsal.setEditable(false);
            txtEdat.setEditable(false);
            btnPrimer.setEnabled(false);
            btnAnterior.setEnabled(false);
            btnSeguent.setEnabled(false);
            btnUltim.setEnabled(false);
        }
    }
    
     /**
     * Activa o desactiva els botons en funció de si estem en el primer o darrer
     * registre
     * @param pucEnrere true si puc tirar enrere, false en cas contrari
     * @param pucEndavant true si puc tirar endavant, false en cas contrari
     */
    private void actualitzarBotons(){
        
        /*Aquest mètode hauria d'activar o desactivar els botons
        en funció de si estem o no en el primer registre o l'últim*/
        btnPrimer.setEnabled(llistaJugadors.pucEnrere());
        btnAnterior.setEnabled(llistaJugadors.pucEnrere());
        btnSeguent.setEnabled(llistaJugadors.pucEndavant());
        btnUltim.setEnabled(llistaJugadors.pucEndavant());
    }
    
    private Jugador recuperarJugador() {
        Jugador jugador = new Jugador();
        jugador.setJugId(Integer.parseInt(txtIdJugador.getText()));
        jugador.setEqId(Integer.parseInt(txtIdEquip.getText()));
        jugador.setJugNom(txtNomJugador.getText());
        jugador.setDorsal(Integer.parseInt(txtDorsal.getText()));
        jugador.setEdat(Integer.parseInt(txtEdat.getText()));
        return jugador;
    }
    
    private void modificarJugadors() {
        Jugador jugador = recuperarJugador();
        if (llistaJugadors.actual().compareTo(jugador) != 0) {
            llistaJugadors.updateJugador(jugador);
        }
    }
    
    public void getLlistaJugadors() {
        Jugadors llista = llistaJugadors;
        llista.obtenirJugadorsByEquip(idEquip);
        Primer();
    }
    
    /*
    Feu una ullada als mètodes:
    private void btnSortirActionPerformed(java.awt.event.ActionEvent evt)
    private void btnPrimerActionPerformed(java.awt.event.ActionEvent evt)
    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt)
    private void btnSeguentActionPerformed(java.awt.event.ActionEvent evt)
    private void btnUltimActionPerformed(java.awt.event.ActionEvent evt)
    public static void main(String args[])
    */

    /*
    *  Entre els atributs privats de la classe necessitarem un objecte de tipus Equips
    *  dels que heu creat als vostres projectes, Aquest objecte l'haureu d'inicialitzar
    *  en el main. En els mètodes primer, anterior, últim, seguent haureu de cridar els
    *  mètodes corresponents de l'objecte Equips que teniu en memòria
    *  Haureu d'afegir, si és que no ho teniu, a la Classe Equips un mètode que us indiqui
    *  si podeu tirar enrere i un altre que us indiqui si podeu tirar endavant. D'aquesta
    *  manera podreu activar i desactivar els corresponents botons.
    *
    */

}